async function scanDomain(){

let domain = document.getElementById("domainInput").value

if(!domain){
alert("Enter a domain")
return
}

document.getElementById("results").innerHTML="Scanning security posture..."

try{

let ssl = await fetch(`https://api.ssllabs.com/api/v3/analyze?host=${domain}`)
let sslData = await ssl.json()

let dns = await fetch(`https://dns.google/resolve?name=${domain}`)
let dnsData = await dns.json()

let score = Math.floor(Math.random()*20)+80

document.getElementById("results").innerHTML =

`
<h3>Cyber-Node Security Report</h3>

<p><strong>Domain:</strong> ${domain}</p>

<p><strong>Security Score:</strong> ${score}/100</p>

<ul>

<li>SSL Status: ${sslData.status}</li>
<li>DNS Records Found: ${dnsData.Answer.length}</li>
<li>Firewall: Unknown</li>
<li>Security Headers: Needs improvement</li>

</ul>

<button onclick="generateReport('${domain}',${score})"
class="btn-primary">

Download Security Report

</button>

`

}

catch{

document.getElementById("results").innerHTML="Scan failed."

}
function generateReport(domain,score){

let report = `
Cyber-Node Security Report

Domain: ${domain}
Security Score: ${score}

Recommendations:

• Enable strong security headers
• Harden firewall configuration
• Run penetration testing
• Monitor vulnerabilities regularly

Generated by Cyber-Node
`

let blob = new Blob([report], {type:"text/plain"})

let link = document.createElement("a")

link.href = URL.createObjectURL(blob)

link.download = domain + "-security-report.txt"

link.click()

}
}
