async function scanDomain(){

let domain = document.getElementById("domainInput").value

if(!domain){
alert("Enter a domain")
return
}

document.getElementById("results").innerHTML="Running Cyber-Node security scan..."

try{

let ssl = await fetch(`https://api.ssllabs.com/api/v3/analyze?host=${domain}`)
let sslData = await ssl.json()

let dns = await fetch(`https://dns.google/resolve?name=${domain}`)
let dnsData = await dns.json()

let tech = fingerprintTechnology(domain)

let vulnerabilities = checkVulnerabilities(tech)

let score = calculateRisk(vulnerabilities)

displayResults(domain,score,sslData.status,dnsData.Answer.length,tech,vulnerabilities)

saveScan(domain,score)

}

catch{

document.getElementById("results").innerHTML="Scan failed."

}

}



function fingerprintTechnology(domain){

if(domain.includes("wordpress")) return "WordPress"
if(domain.includes("shop")) return "Shop Platform"
if(domain.includes("node")) return "Node.js"

return "Generic Web Server"

}



function checkVulnerabilities(tech){

let database = {

"WordPress":[
"CVE-2023-45124",
"CVE-2024-1012"
],

"Node.js":[
"CVE-2023-23918"
],

"Generic Web Server":[
"Possible outdated packages"
]

}

return database[tech] || []

}



function calculateRisk(vulns){

if(vulns.length==0) return 90

if(vulns.length==1) return 75

if(vulns.length>=2) return 60

}



function displayResults(domain,score,sslStatus,dnsCount,tech,vulns){

let vulnList = vulns.map(v => `<li>${v}</li>`).join("")

document.getElementById("results").innerHTML =

`
<h3>Cyber-Node Security Intelligence Report</h3>

<p><strong>Domain:</strong> ${domain}</p>
<p><strong>Security Score:</strong> ${score}/100</p>

<ul>
<li>SSL Status: ${sslStatus}</li>
<li>DNS Records: ${dnsCount}</li>
<li>Technology Stack: ${tech}</li>
</ul>

<h4>Known Vulnerabilities</h4>

<ul>
${vulnList}
</ul>

<button onclick="generateReport('${domain}',${score})"
class="btn-primary">

Download Security Report

</button>

`

}



function generateReport(domain,score){

let report = `
Cyber-Node Security Intelligence Report

Domain: ${domain}
Security Score: ${score}/100

Recommended Actions
-------------------

• Update outdated software
• Apply security patches
• Enable strong security headers
• Implement firewall monitoring

Generated by Cyber-Node
`

let blob = new Blob([report],{type:"text/plain"})

let link=document.createElement("a")

link.href=URL.createObjectURL(blob)

link.download=domain+"-security-report.txt"

link.click()

}



function saveScan(domain,score){

let scans = JSON.parse(localStorage.getItem("scans") || "[]")

scans.push({
domain:domain,
score:score,
date:new Date().toLocaleDateString()
})

localStorage.setItem("scans",JSON.stringify(scans))

}
